// Command shardcorpus distributes generated loaders into internal packages.
// It preserves Go declarations and source strings; only loader identifiers
// become exported so the generated registry can refer to internal packages.
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

const module = "github.com/tarekwasfy01/RTDAL---R-Transpiled-Data-Abstraction-Library"

var loader = regexp.MustCompile(`^loadRTDAL([0-9]{6})(Part[0-9]+)?$`)
var sourceName = regexp.MustCompile(`^rtdal([0-9]{6})`)

func main() {
	paths, err := filepath.Glob("generated/corpus_part_*.go")
	if err != nil {
		panic(err)
	}
	for _, extra := range []string{"generated/corpus_prelude.go", "generated/RTDAL_ALL_TRANSPILED.go"} {
		if _, err := os.Stat(extra); err == nil {
			paths = append(paths, extra)
		}
	}
	if len(paths) == 0 {
		fmt.Println("Corpus already sharded.")
		return
	}
	chunks := map[int]*strings.Builder{}
	var registry strings.Builder
	registrations := 0
	for _, path := range paths {
		data, err := os.ReadFile(path)
		if err != nil {
			panic(err)
		}
		fset := token.NewFileSet()
		file, err := parser.ParseFile(fset, path, data, parser.ParseComments)
		if err != nil {
			panic(err)
		}
		offset := func(p token.Pos) int { return fset.Position(p).Offset }
		for _, decl := range file.Decls {
			name, doc := "", (*ast.CommentGroup)(nil)
			switch d := decl.(type) {
			case *ast.FuncDecl:
				name, doc = d.Name.Name, d.Doc
			case *ast.GenDecl:
				if d.Tok == token.IMPORT {
					continue
				}
				doc = d.Doc
				if len(d.Specs) != 1 {
					panic("unexpected grouped declaration in " + path)
				}
				switch spec := d.Specs[0].(type) {
				case *ast.ValueSpec:
					if len(spec.Names) != 1 {
						panic("unexpected grouped names")
					}
					name = spec.Names[0].Name
				case *ast.TypeSpec:
					name = spec.Name.Name
				}
			}
			if name == "_" {
				continue
			}
			part := partFor(name)
			start, end := offset(decl.Pos()), offset(decl.End())
			if doc != nil {
				start = offset(doc.Pos())
			}
			type edit struct {
				start, end int
				text       string
			}
			var edits []edit
			ast.Inspect(decl, func(node ast.Node) bool {
				id, ok := node.(*ast.Ident)
				if !ok || !loader.MatchString(id.Name) {
					return true
				}
				replacement := "L" + id.Name[1:]
				if part == 0 {
					replacement = fmt.Sprintf("part%03d.%s", partFor(id.Name), replacement)
					registrations++
				}
				edits = append(edits, edit{offset(id.Pos()), offset(id.End()), replacement})
				return true
			})
			sort.Slice(edits, func(i, j int) bool { return edits[i].start < edits[j].start })
			var text strings.Builder
			cursor := start
			for _, e := range edits {
				text.Write(data[cursor:e.start])
				text.WriteString(e.text)
				cursor = e.end
			}
			text.Write(data[cursor:end])
			text.WriteString("\n\n")
			if part == 0 {
				registry.WriteString(text.String())
			} else {
				if chunks[part] == nil {
					chunks[part] = &strings.Builder{}
				}
				chunks[part].WriteString(text.String())
			}
		}
	}
	var parts []int
	for part := range chunks {
		parts = append(parts, part)
	}
	sort.Ints(parts)
	header := "// Code generated by RTDAL and shardcorpus. DO NOT EDIT.\n"
	var root strings.Builder
	root.WriteString(header + "package generated\n\nimport (\n\"fmt\"\n\"" + module + "/toolchain/r2go/runtime\"\n")
	for _, part := range parts {
		pkg := fmt.Sprintf("part%03d", part)
		fmt.Fprintf(&root, "%s \"%s/generated/internal/%s\"\n", pkg, module, pkg)
		dir := filepath.Join("generated", "internal", pkg)
		if err := os.MkdirAll(dir, 0755); err != nil {
			panic(err)
		}
		text := header + "package " + pkg + "\n\nimport (\"fmt\"; \"" + module + "/toolchain/r2go/runtime\")\nvar _ = fmt.Errorf\n\n" + chunks[part].String()
		writeGo(filepath.Join(dir, "loaders.go"), text)
	}
	root.WriteString(")\n\n" + registry.String())
	writeGo("generated/registry.go", root.String())
	for _, path := range paths {
		if err := os.Remove(path); err != nil {
			panic(err)
		}
	}
	fmt.Printf("Preserved %d registry entries across %d internal packages.\n", registrations, len(parts))
}

func partFor(name string) int {
	m := loader.FindStringSubmatch(name)
	if m == nil {
		m = sourceName.FindStringSubmatch(name)
	}
	if m == nil {
		return 0
	}
	id, err := strconv.Atoi(m[1])
	if err != nil {
		panic(err)
	}
	return (id-1)/256 + 1
}

func writeGo(path, text string) {
	if _, err := parser.ParseFile(token.NewFileSet(), path, text, 0); err != nil {
		panic(err)
	}
	if err := os.WriteFile(path, []byte(text), 0644); err != nil {
		panic(err)
	}
}
