package rprimitive

// PrimitiveHandler is the translated GNU R primitive signature.
type PrimitiveHandler func(call, op, args, env Value) Value

type PrimitiveDescriptor struct {
	Name       string
	CEntry     string
	Offset     int
	SourceFile string
	Batch      string
	Handler    PrimitiveHandler
}

var PrimitiveTable = map[string]PrimitiveDescriptor{
	".External":                 {Name: ".External", CEntry: "do_External", Offset: 0, SourceFile: "src/main/dotcode.c", Batch: "batch_001.c", Handler: do_External},
	".External2":                {Name: ".External2", CEntry: "do_External", Offset: 1, SourceFile: "src/main/dotcode.c", Batch: "batch_001.c", Handler: do_External},
	".External.graphics":        {Name: ".External.graphics", CEntry: "do_Externalgr", Offset: 0, SourceFile: "src/main/dotcode.c", Batch: "batch_002.c", Handler: do_Externalgr},
	"activeBindingFunction":     {Name: "activeBindingFunction", CEntry: "do_activeBndFun", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_003.c", Handler: do_activeBndFun},
	".addCondHands":             {Name: ".addCondHands", CEntry: "do_addCondHands", Offset: 0, SourceFile: "src/main/errors.c", Batch: "batch_004.c", Handler: do_addCondHands},
	".addGlobHands":             {Name: ".addGlobHands", CEntry: "do_addGlobHands", Offset: 0, SourceFile: "src/main/errors.c", Batch: "batch_005.c", Handler: do_addGlobHands},
	".addRestart":               {Name: ".addRestart", CEntry: "do_addRestart", Offset: 0, SourceFile: "src/main/errors.c", Batch: "batch_006.c", Handler: do_addRestart},
	".addTryHandlers":           {Name: ".addTryHandlers", CEntry: "do_addTryHandlers", Offset: 0, SourceFile: "src/main/errors.c", Batch: "batch_007.c", Handler: do_addTryHandlers},
	"as.environment":            {Name: "as.environment", CEntry: "do_as_environment", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_008.c", Handler: do_as_environment},
	"as.function.default":       {Name: "as.function.default", CEntry: "do_asfunction", Offset: 0, SourceFile: "src/main/coerce.c", Batch: "batch_009.c", Handler: do_asfunction},
	"attach":                    {Name: "attach", CEntry: "do_attach", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_010.c", Handler: do_attach},
	"bcClose":                   {Name: "bcClose", CEntry: "do_bcclose", Offset: 0, SourceFile: "src/main/eval.c", Batch: "batch_011.c", Handler: do_bcclose},
	"bcprofcounts":              {Name: "bcprofcounts", CEntry: "do_bcprofcounts", Offset: 0, SourceFile: "src/main/eval.c", Batch: "batch_012.c", Handler: do_bcprofcounts},
	"bcprofstart":               {Name: "bcprofstart", CEntry: "do_bcprofstart", Offset: 0, SourceFile: "src/main/eval.c", Batch: "batch_013.c", Handler: do_bcprofstart},
	"bcprofstop":                {Name: "bcprofstop", CEntry: "do_bcprofstop", Offset: 0, SourceFile: "src/main/eval.c", Batch: "batch_014.c", Handler: do_bcprofstop},
	"getBindingType":            {Name: "getBindingType", CEntry: "do_bindingType", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_015.c", Handler: do_bindingType},
	"bindingIsActive":           {Name: "bindingIsActive", CEntry: "do_bndIsActive", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_016.c", Handler: do_bndIsActive},
	"bindingIsLocked":           {Name: "bindingIsLocked", CEntry: "do_bndIsLocked", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_017.c", Handler: do_bndIsLocked},
	"bodyCode":                  {Name: "bodyCode", CEntry: "do_bodyCode", Offset: 0, SourceFile: "src/main/builtin.c", Batch: "batch_018.c", Handler: do_bodyCode},
	"builtins":                  {Name: "builtins", CEntry: "do_builtins", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_019.c", Handler: do_builtins},
	"curlDownload":              {Name: "curlDownload", CEntry: "do_curlDownload", Offset: 0, SourceFile: "src/main/internet.c", Batch: "batch_020.c", Handler: do_curlDownload},
	"curlGetHeaders":            {Name: "curlGetHeaders", CEntry: "do_curlGetHeaders", Offset: 0, SourceFile: "src/main/internet.c", Batch: "batch_021.c", Handler: do_curlGetHeaders},
	"curlVersion":               {Name: "curlVersion", CEntry: "do_curlVersion", Offset: 0, SourceFile: "src/main/internet.c", Batch: "batch_022.c", Handler: do_curlVersion},
	"debug":                     {Name: "debug", CEntry: "do_debug", Offset: 0, SourceFile: "src/main/debug.c", Batch: "batch_023.c", Handler: do_debug},
	"debugonce":                 {Name: "debugonce", CEntry: "do_debug", Offset: 3, SourceFile: "src/main/debug.c", Batch: "batch_023.c", Handler: do_debug},
	"isdebugged":                {Name: "isdebugged", CEntry: "do_debug", Offset: 2, SourceFile: "src/main/debug.c", Batch: "batch_023.c", Handler: do_debug},
	"undebug":                   {Name: "undebug", CEntry: "do_debug", Offset: 1, SourceFile: "src/main/debug.c", Batch: "batch_023.c", Handler: do_debug},
	"declare":                   {Name: "declare", CEntry: "do_declare", Offset: 0, SourceFile: "src/main/eval.c", Batch: "batch_024.c", Handler: do_declare},
	"delayedAssign":             {Name: "delayedAssign", CEntry: "do_delayed", Offset: 0, SourceFile: "src/main/builtin.c", Batch: "batch_025.c", Handler: do_delayed},
	"delayedBindingEnvironment": {Name: "delayedBindingEnvironment", CEntry: "do_delayedBindingEnv", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_026.c", Handler: do_delayedBindingEnv},
	"delayedBindingExpression":  {Name: "delayedBindingExpression", CEntry: "do_delayedBindingExpr", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_027.c", Handler: do_delayedBindingExpr},
	"detach":                    {Name: "detach", CEntry: "do_detach", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_028.c", Handler: do_detach},
	"disassemble":               {Name: "disassemble", CEntry: "do_disassemble", Offset: 0, SourceFile: "src/main/eval.c", Batch: "batch_029.c", Handler: do_disassemble},
	"do.call":                   {Name: "do.call", CEntry: "do_docall", Offset: 0, SourceFile: "src/main/coerce.c", Batch: "batch_030.c", Handler: do_docall},
	".C":                        {Name: ".C", CEntry: "do_dotCode", Offset: 0, SourceFile: "src/main/dotcode.c", Batch: "batch_031.c", Handler: do_dotCode},
	".Fortran":                  {Name: ".Fortran", CEntry: "do_dotCode", Offset: 1, SourceFile: "src/main/dotcode.c", Batch: "batch_031.c", Handler: do_dotCode},
	"dotDelayedEnvironment":     {Name: "dotDelayedEnvironment", CEntry: "do_dotDelayedEnv", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_032.c", Handler: do_dotDelayedEnv},
	"dotDelayedExpression":      {Name: "dotDelayedExpression", CEntry: "do_dotDelayedExpr", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_033.c", Handler: do_dotDelayedExpr},
	"dotForcedExpression":       {Name: "dotForcedExpression", CEntry: "do_dotForcedExpr", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_034.c", Handler: do_dotForcedExpr},
	"getDotType":                {Name: "getDotType", CEntry: "do_dotType", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_035.c", Handler: do_dotType},
	".Call":                     {Name: ".Call", CEntry: "do_dotcall", Offset: 0, SourceFile: "src/main/dotcode.c", Batch: "batch_036.c", Handler: do_dotcall},
	".Call.graphics":            {Name: ".Call.graphics", CEntry: "do_dotcallgr", Offset: 0, SourceFile: "src/main/dotcode.c", Batch: "batch_037.c", Handler: do_dotcallgr},
	"dump":                      {Name: "dump", CEntry: "do_dump", Offset: 0, SourceFile: "src/main/deparse.c", Batch: "batch_038.c", Handler: do_dump},
	"dyn.load":                  {Name: "dyn.load", CEntry: "do_dynload", Offset: 0, SourceFile: "src/main/Rdynload.c", Batch: "batch_039.c", Handler: do_dynload},
	"dyn.unload":                {Name: "dyn.unload", CEntry: "do_dynunload", Offset: 0, SourceFile: "src/main/Rdynload.c", Batch: "batch_040.c", Handler: do_dynunload},
	"eapply":                    {Name: "eapply", CEntry: "do_eapply", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_041.c", Handler: do_eapply},
	"env2list":                  {Name: "env2list", CEntry: "do_env2list", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_042.c", Handler: do_env2list},
	"environmentIsLocked":       {Name: "environmentIsLocked", CEntry: "do_envIsLocked", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_043.c", Handler: do_envIsLocked},
	"environmentName":           {Name: "environmentName", CEntry: "do_envirName", Offset: 0, SourceFile: "src/main/builtin.c", Batch: "batch_044.c", Handler: do_envirName},
	"environment<-":             {Name: "environment<-", CEntry: "do_envirgets", Offset: 0, SourceFile: "src/main/builtin.c", Batch: "batch_045.c", Handler: do_envirgets},
	"env.profile":               {Name: "env.profile", CEntry: "do_envprofile", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_046.c", Handler: do_envprofile},
	"fifo":                      {Name: "fifo", CEntry: "do_fifo", Offset: 0, SourceFile: "src/main/connections.c", Batch: "batch_047.c", Handler: do_fifo},
	"forcedBindingExpression":   {Name: "forcedBindingExpression", CEntry: "do_forcedBindingExpr", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_048.c", Handler: do_forcedBindingExpr},
	"getLoadedDLLs":             {Name: "getLoadedDLLs", CEntry: "do_getDllTable", Offset: 0, SourceFile: "src/main/Rdynload.c", Batch: "batch_049.c", Handler: do_getDllTable},
	"getNamespaceRegistry":      {Name: "getNamespaceRegistry", CEntry: "do_getNSRegistry", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_050.c", Handler: do_getNSRegistry},
	"getNamespaceValue":         {Name: "getNamespaceValue", CEntry: "do_getNSValue", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_051.c", Handler: do_getNSValue},
	"getRegisteredNamespace":    {Name: "getRegisteredNamespace", CEntry: "do_getRegNS", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_052.c", Handler: do_getRegNS},
	"isRegisteredNamespace":     {Name: "isRegisteredNamespace", CEntry: "do_getRegNS", Offset: 1, SourceFile: "src/main/envir.c", Batch: "batch_052.c", Handler: do_getRegNS},
	"getRegisteredRoutines":     {Name: "getRegisteredRoutines", CEntry: "do_getRegisteredRoutines", Offset: 0, SourceFile: "src/main/Rdynload.c", Batch: "batch_053.c", Handler: do_getRegisteredRoutines},
	"getSymbolInfo":             {Name: "getSymbolInfo", CEntry: "do_getSymbolInfo", Offset: 0, SourceFile: "src/main/Rdynload.c", Batch: "batch_054.c", Handler: do_getSymbolInfo},
	"getVarsFromFrame":          {Name: "getVarsFromFrame", CEntry: "do_getVarsFromFrame", Offset: 0, SourceFile: "src/main/serialize.c", Batch: "batch_055.c", Handler: do_getVarsFromFrame},
	"getconst":                  {Name: "getconst", CEntry: "do_getconst", Offset: 0, SourceFile: "src/main/eval.c", Batch: "batch_056.c", Handler: do_getconst},
	"growconst":                 {Name: "growconst", CEntry: "do_growconst", Offset: 0, SourceFile: "src/main/eval.c", Batch: "batch_057.c", Handler: do_growconst},
	"gzcon":                     {Name: "gzcon", CEntry: "do_gzcon", Offset: 0, SourceFile: "src/main/connections.c", Batch: "batch_058.c", Handler: do_gzcon},
	"bzfile":                    {Name: "bzfile", CEntry: "do_gzfile", Offset: 1, SourceFile: "src/main/connections.c", Batch: "batch_059.c", Handler: do_gzfile},
	"gzfile":                    {Name: "gzfile", CEntry: "do_gzfile", Offset: 0, SourceFile: "src/main/connections.c", Batch: "batch_059.c", Handler: do_gzfile},
	"xzfile":                    {Name: "xzfile", CEntry: "do_gzfile", Offset: 2, SourceFile: "src/main/connections.c", Batch: "batch_059.c", Handler: do_gzfile},
	"zstdfile":                  {Name: "zstdfile", CEntry: "do_gzfile", Offset: 3, SourceFile: "src/main/connections.c", Batch: "batch_059.c", Handler: do_gzfile},
	"importIntoEnv":             {Name: "importIntoEnv", CEntry: "do_importIntoEnv", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_060.c", Handler: do_importIntoEnv},
	"inspect":                   {Name: "inspect", CEntry: "do_inspect", Offset: 0, SourceFile: "src/main/inspect.c", Batch: "batch_061.c", Handler: do_inspect},
	".invokeRestart":            {Name: ".invokeRestart", CEntry: "do_invokeRestart", Offset: 0, SourceFile: "src/main/errors.c", Batch: "batch_062.c", Handler: do_invokeRestart},
	"isNamespaceEnv":            {Name: "isNamespaceEnv", CEntry: "do_isNSEnv", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_063.c", Handler: do_isNSEnv},
	"is.builtin.internal":       {Name: "is.builtin.internal", CEntry: "do_is_builtin_internal", Offset: 0, SourceFile: "src/main/eval.c", Batch: "batch_064.c", Handler: do_is_builtin_internal},
	"is.loaded":                 {Name: "is.loaded", CEntry: "do_isloaded", Offset: 0, SourceFile: "src/main/dotcode.c", Batch: "batch_065.c", Handler: do_isloaded},
	"La_qr_cmplx":               {Name: "La_qr_cmplx", CEntry: "do_lapack", Offset: 0, SourceFile: "src/main/lapack.c", Batch: "batch_066.c", Handler: do_lapack},
	"La_rg":                     {Name: "La_rg", CEntry: "do_lapack", Offset: 3, SourceFile: "src/main/lapack.c", Batch: "batch_066.c", Handler: do_lapack},
	"La_rg_cmplx":               {Name: "La_rg_cmplx", CEntry: "do_lapack", Offset: 41, SourceFile: "src/main/lapack.c", Batch: "batch_066.c", Handler: do_lapack},
	"La_rs":                     {Name: "La_rs", CEntry: "do_lapack", Offset: 1, SourceFile: "src/main/lapack.c", Batch: "batch_066.c", Handler: do_lapack},
	"La_rs_cmplx":               {Name: "La_rs_cmplx", CEntry: "do_lapack", Offset: 2, SourceFile: "src/main/lapack.c", Batch: "batch_066.c", Handler: do_lapack},
	"La_solve_cmplx":            {Name: "La_solve_cmplx", CEntry: "do_lapack", Offset: 11, SourceFile: "src/main/lapack.c", Batch: "batch_066.c", Handler: do_lapack},
	"La_svd":                    {Name: "La_svd", CEntry: "do_lapack", Offset: 400, SourceFile: "src/main/lapack.c", Batch: "batch_066.c", Handler: do_lapack},
	"La_svd_cmplx":              {Name: "La_svd_cmplx", CEntry: "do_lapack", Offset: 401, SourceFile: "src/main/lapack.c", Batch: "batch_066.c", Handler: do_lapack},
	"La_zgecon":                 {Name: "La_zgecon", CEntry: "do_lapack", Offset: 9, SourceFile: "src/main/lapack.c", Batch: "batch_066.c", Handler: do_lapack},
	"La_ztrcon":                 {Name: "La_ztrcon", CEntry: "do_lapack", Offset: 10, SourceFile: "src/main/lapack.c", Batch: "batch_066.c", Handler: do_lapack},
	"La_ztrcon3":                {Name: "La_ztrcon3", CEntry: "do_lapack", Offset: 13, SourceFile: "src/main/lapack.c", Batch: "batch_066.c", Handler: do_lapack},
	"qr_coef_cmplx":             {Name: "qr_coef_cmplx", CEntry: "do_lapack", Offset: 303, SourceFile: "src/main/lapack.c", Batch: "batch_066.c", Handler: do_lapack},
	"qr_coef_real":              {Name: "qr_coef_real", CEntry: "do_lapack", Offset: 300, SourceFile: "src/main/lapack.c", Batch: "batch_066.c", Handler: do_lapack},
	"qr_qy_cmplx":               {Name: "qr_qy_cmplx", CEntry: "do_lapack", Offset: 304, SourceFile: "src/main/lapack.c", Batch: "batch_066.c", Handler: do_lapack},
	"qr_qy_real":                {Name: "qr_qy_real", CEntry: "do_lapack", Offset: 301, SourceFile: "src/main/lapack.c", Batch: "batch_066.c", Handler: do_lapack},
	"lazyLoadDBfetch":           {Name: "lazyLoadDBfetch", CEntry: "do_lazyLoadDBfetch", Offset: 0, SourceFile: "src/main/serialize.c", Batch: "batch_067.c", Handler: do_lazyLoadDBfetch},
	"lazyLoadDBflush":           {Name: "lazyLoadDBflush", CEntry: "do_lazyLoadDBflush", Offset: 0, SourceFile: "src/main/serialize.c", Batch: "batch_068.c", Handler: do_lazyLoadDBflush},
	"lazyLoadDBinsertValue":     {Name: "lazyLoadDBinsertValue", CEntry: "do_lazyLoadDBinsertValue", Offset: 0, SourceFile: "src/main/serialize.c", Batch: "batch_069.c", Handler: do_lazyLoadDBinsertValue},
	"list2env":                  {Name: "list2env", CEntry: "do_list2env", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_070.c", Handler: do_list2env},
	"load":                      {Name: "load", CEntry: "do_load", Offset: 0, SourceFile: "src/main/saveload.c", Batch: "batch_071.c", Handler: do_load},
	"loadFromConn2":             {Name: "loadFromConn2", CEntry: "do_loadFromConn2", Offset: 0, SourceFile: "src/main/saveload.c", Batch: "batch_072.c", Handler: do_loadFromConn2},
	"loadInfoFromConn2":         {Name: "loadInfoFromConn2", CEntry: "do_loadFromConn2", Offset: 1, SourceFile: "src/main/saveload.c", Batch: "batch_072.c", Handler: do_loadFromConn2},
	"load.from.file":            {Name: "load.from.file", CEntry: "do_loadfile", Offset: 0, SourceFile: "src/main/saveload.c", Batch: "batch_073.c", Handler: do_loadfile},
	"lockBinding":               {Name: "lockBinding", CEntry: "do_lockBnd", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_074.c", Handler: do_lockBnd},
	"unlockBinding":             {Name: "unlockBinding", CEntry: "do_lockBnd", Offset: 1, SourceFile: "src/main/envir.c", Batch: "batch_074.c", Handler: do_lockBnd},
	"lockEnvironment":           {Name: "lockEnvironment", CEntry: "do_lockEnv", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_075.c", Handler: do_lockEnv},
	"ls":                        {Name: "ls", CEntry: "do_ls", Offset: 1, SourceFile: "src/main/envir.c", Batch: "batch_076.c", Handler: do_ls},
	"makeLazy":                  {Name: "makeLazy", CEntry: "do_makelazy", Offset: 0, SourceFile: "src/main/builtin.c", Batch: "batch_077.c", Handler: do_makelazy},
	"match.call":                {Name: "match.call", CEntry: "do_matchcall", Offset: 0, SourceFile: "src/main/unique.c", Batch: "batch_078.c", Handler: do_matchcall},
	"mget":                      {Name: "mget", CEntry: "do_mget", Offset: 1, SourceFile: "src/main/envir.c", Batch: "batch_079.c", Handler: do_mget},
	"makeActiveBinding":         {Name: "makeActiveBinding", CEntry: "do_mkActiveBnd", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_080.c", Handler: do_mkActiveBnd},
	"mkUnbound":                 {Name: "mkUnbound", CEntry: "do_mkUnbound", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_081.c", Handler: do_mkUnbound},
	"mkCode":                    {Name: "mkCode", CEntry: "do_mkcode", Offset: 0, SourceFile: "src/main/eval.c", Batch: "batch_082.c", Handler: do_mkcode},
	"mmap_file":                 {Name: "mmap_file", CEntry: "do_mmap_file", Offset: 0, SourceFile: "src/main/altclasses.c", Batch: "batch_083.c", Handler: do_mmap_file},
	"munmap_file":               {Name: "munmap_file", CEntry: "do_munmap_file", Offset: 0, SourceFile: "src/main/altclasses.c", Batch: "batch_084.c", Handler: do_munmap_file},
	"on.exit":                   {Name: "on.exit", CEntry: "do_onexit", Offset: 0, SourceFile: "src/main/builtin.c", Batch: "batch_085.c", Handler: do_onexit},
	"parent.env<-":              {Name: "parent.env<-", CEntry: "do_parentenvgets", Offset: 0, SourceFile: "src/main/builtin.c", Batch: "batch_086.c", Handler: do_parentenvgets},
	"pipe":                      {Name: "pipe", CEntry: "do_pipe", Offset: 0, SourceFile: "src/main/connections.c", Batch: "batch_087.c", Handler: do_pipe},
	"pos.to.env":                {Name: "pos.to.env", CEntry: "do_pos2env", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_088.c", Handler: do_pos2env},
	"putconst":                  {Name: "putconst", CEntry: "do_putconst", Offset: 0, SourceFile: "src/main/eval.c", Batch: "batch_089.c", Handler: do_putconst},
	"readline":                  {Name: "readline", CEntry: "do_readln", Offset: 0, SourceFile: "src/main/scan.c", Batch: "batch_090.c", Handler: do_readln},
	"Recall":                    {Name: "Recall", CEntry: "do_recall", Offset: 0, SourceFile: "src/main/eval.c", Batch: "batch_091.c", Handler: do_recall},
	"recordGraphics":            {Name: "recordGraphics", CEntry: "do_recordGraphics", Offset: 0, SourceFile: "src/main/engine.c", Batch: "batch_092.c", Handler: do_recordGraphics},
	"reg.finalizer":             {Name: "reg.finalizer", CEntry: "do_regFinaliz", Offset: 0, SourceFile: "src/main/memory.c", Batch: "batch_093.c", Handler: do_regFinaliz},
	"registerNamespace":         {Name: "registerNamespace", CEntry: "do_regNS", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_094.c", Handler: do_regNS},
	"remove":                    {Name: "remove", CEntry: "do_remove", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_095.c", Handler: do_remove},
	"save":                      {Name: "save", CEntry: "do_save", Offset: 0, SourceFile: "src/main/saveload.c", Batch: "batch_096.c", Handler: do_save},
	"saveToConn":                {Name: "saveToConn", CEntry: "do_saveToConn", Offset: 0, SourceFile: "src/main/saveload.c", Batch: "batch_097.c", Handler: do_saveToConn},
	"save.to.file":              {Name: "save.to.file", CEntry: "do_savefile", Offset: 0, SourceFile: "src/main/saveload.c", Batch: "batch_098.c", Handler: do_savefile},
	"scan":                      {Name: "scan", CEntry: "do_scan", Offset: 0, SourceFile: "src/main/scan.c", Batch: "batch_099.c", Handler: do_scan},
	"search":                    {Name: "search", CEntry: "do_search", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_100.c", Handler: do_search},
	"serializeb":                {Name: "serializeb", CEntry: "do_serialize", Offset: 1, SourceFile: "src/main/serialize.c", Batch: "batch_101.c", Handler: do_serialize},
	"serializeToConn":           {Name: "serializeToConn", CEntry: "do_serializeToConn", Offset: 0, SourceFile: "src/main/serialize.c", Batch: "batch_102.c", Handler: do_serializeToConn},
	"serverSocket":              {Name: "serverSocket", CEntry: "do_serversocket", Offset: 0, SourceFile: "src/main/connections.c", Batch: "batch_103.c", Handler: do_serversocket},
	"shell.exec":                {Name: "shell.exec", CEntry: "do_shellexec", Offset: 0, SourceFile: "src/gnuwin32/extra.c", Batch: "batch_104.c", Handler: do_shellexec},
	".signalCondition":          {Name: ".signalCondition", CEntry: "do_signalCondition", Offset: 0, SourceFile: "src/main/errors.c", Batch: "batch_105.c", Handler: do_signalCondition},
	"socketAccept":              {Name: "socketAccept", CEntry: "do_sockconn", Offset: 1, SourceFile: "src/main/connections.c", Batch: "batch_106.c", Handler: do_sockconn},
	"socketConnection":          {Name: "socketConnection", CEntry: "do_sockconn", Offset: 0, SourceFile: "src/main/connections.c", Batch: "batch_106.c", Handler: do_sockconn},
	"standardGeneric":           {Name: "standardGeneric", CEntry: "do_standardGeneric", Offset: 0, SourceFile: "src/main/objects.c", Batch: "batch_107.c", Handler: do_standardGeneric},
	"substitute":                {Name: "substitute", CEntry: "do_substitute", Offset: 0, SourceFile: "src/main/coerce.c", Batch: "batch_108.c", Handler: do_substitute},
	"sys.call":                  {Name: "sys.call", CEntry: "do_sys", Offset: 2, SourceFile: "src/main/context.c", Batch: "batch_109.c", Handler: do_sys},
	"sys.calls":                 {Name: "sys.calls", CEntry: "do_sys", Offset: 5, SourceFile: "src/main/context.c", Batch: "batch_109.c", Handler: do_sys},
	"sys.frame":                 {Name: "sys.frame", CEntry: "do_sys", Offset: 3, SourceFile: "src/main/context.c", Batch: "batch_109.c", Handler: do_sys},
	"sys.frames":                {Name: "sys.frames", CEntry: "do_sys", Offset: 6, SourceFile: "src/main/context.c", Batch: "batch_109.c", Handler: do_sys},
	"sys.function":              {Name: "sys.function", CEntry: "do_sys", Offset: 9, SourceFile: "src/main/context.c", Batch: "batch_109.c", Handler: do_sys},
	"sys.nframe":                {Name: "sys.nframe", CEntry: "do_sys", Offset: 4, SourceFile: "src/main/context.c", Batch: "batch_109.c", Handler: do_sys},
	"sys.on.exit":               {Name: "sys.on.exit", CEntry: "do_sys", Offset: 7, SourceFile: "src/main/context.c", Batch: "batch_109.c", Handler: do_sys},
	"sys.parent":                {Name: "sys.parent", CEntry: "do_sys", Offset: 1, SourceFile: "src/main/context.c", Batch: "batch_109.c", Handler: do_sys},
	"sys.parents":               {Name: "sys.parents", CEntry: "do_sys", Offset: 8, SourceFile: "src/main/context.c", Batch: "batch_109.c", Handler: do_sys},
	"browserCondition":          {Name: "browserCondition", CEntry: "do_sysbrowser", Offset: 2, SourceFile: "src/main/context.c", Batch: "batch_110.c", Handler: do_sysbrowser},
	"browserSetDebug":           {Name: "browserSetDebug", CEntry: "do_sysbrowser", Offset: 3, SourceFile: "src/main/context.c", Batch: "batch_110.c", Handler: do_sysbrowser},
	"browserText":               {Name: "browserText", CEntry: "do_sysbrowser", Offset: 1, SourceFile: "src/main/context.c", Batch: "batch_110.c", Handler: do_sysbrowser},
	"Exec":                      {Name: "Exec", CEntry: "do_tailcall", Offset: 0, SourceFile: "src/main/eval.c", Batch: "batch_111.c", Handler: do_tailcall},
	"Tailcall":                  {Name: "Tailcall", CEntry: "do_tailcall", Offset: 1, SourceFile: "src/main/eval.c", Batch: "batch_111.c", Handler: do_tailcall},
	"traceback":                 {Name: "traceback", CEntry: "do_traceback", Offset: 0, SourceFile: "src/main/errors.c", Batch: "batch_112.c", Handler: do_traceback},
	"C_tryCatchHelper":          {Name: "C_tryCatchHelper", CEntry: "do_tryCatchHelper", Offset: 0, SourceFile: "src/main/errors.c", Batch: "batch_113.c", Handler: do_tryCatchHelper},
	"tryWrap":                   {Name: "tryWrap", CEntry: "do_tryWrap", Offset: 0, SourceFile: "src/main/altclasses.c", Batch: "batch_114.c", Handler: do_tryWrap},
	"unregisterNamespace":       {Name: "unregisterNamespace", CEntry: "do_unregNS", Offset: 0, SourceFile: "src/main/envir.c", Batch: "batch_115.c", Handler: do_unregNS},
	"serializeInfoFromConn":     {Name: "serializeInfoFromConn", CEntry: "do_unserializeFromConn", Offset: 1, SourceFile: "src/main/serialize.c", Batch: "batch_116.c", Handler: do_unserializeFromConn},
	"unserializeFromConn":       {Name: "unserializeFromConn", CEntry: "do_unserializeFromConn", Offset: 0, SourceFile: "src/main/serialize.c", Batch: "batch_116.c", Handler: do_unserializeFromConn},
	"unz":                       {Name: "unz", CEntry: "do_unz", Offset: 0, SourceFile: "src/main/connections.c", Batch: "batch_117.c", Handler: do_unz},
	"file":                      {Name: "file", CEntry: "do_url", Offset: 1, SourceFile: "src/main/connections.c", Batch: "batch_118.c", Handler: do_url},
	"url":                       {Name: "url", CEntry: "do_url", Offset: 0, SourceFile: "src/main/connections.c", Batch: "batch_118.c", Handler: do_url},
	"wrap_meta":                 {Name: "wrap_meta", CEntry: "do_wrap_meta", Offset: 0, SourceFile: "src/main/altclasses.c", Batch: "batch_119.c", Handler: do_wrap_meta},
}

func InvokePrimitive(name string, call, op, args, env Value) Value {
	d, ok := PrimitiveTable[name]
	if !ok {
		panic("unknown translated primitive: " + name)
	}
	return d.Handler(call, PrimitiveOp{Primitive: name, Offset: d.Offset, Base: op}, args, env)
}
