param([string]$RTDALPath)
Add-Type -AssemblyName PresentationFramework
$catalog=@{
'Corpus'=@(@('list',''),@('sources','--package <name>'),@('load','--package <name>'))
'Source'=@(@('fetch','[package ...]'),@('fetch-all',''),@('inventory',''),@('licenses',''))
'Transpile'=@(@('corpus',''))
'Vector'=@(@('info','--input <dataset> [--layer <name>] [--json]'),@('convert','--input <dataset> --output <dataset> [--format <driver>]'),@('bbox','--input <dataset> [--layer <name>]'),@('reproject','--input <dataset> --output <dataset> --target-crs <crs>'),@('buffer','--input <dataset> --output <dataset> --distance <value>'),@('simplify','--input <dataset> --output <dataset> --tolerance <value>'),@('centroid','--input <dataset> --output <dataset>'),@('area','--input <dataset> [--geodesic]'),@('length','--input <dataset> [--geodesic]'),@('distance','--input <dataset> --other <dataset>'),@('intersect','--input <dataset> --other <dataset> --output <dataset>'),@('union','--input <dataset> --output <dataset>'),@('difference','--input <dataset> --other <dataset> --output <dataset>'),@('clip','--input <dataset> --mask <dataset> --output <dataset>'),@('validate','--input <dataset> [--repair] [--output <dataset>]'))
'Raster'=@(@('info','--input <dataset> [--json]'),@('convert','--input <dataset> --output <dataset> [--format <driver>]'),@('crop','--input <dataset> --output <dataset> --bbox <xmin,ymin,xmax,ymax>'),@('resample','--input <dataset> --output <dataset> --resolution <x,y>'),@('reproject','--input <dataset> --output <dataset> --target-crs <crs>'),@('mosaic','--input <dataset...> --output <dataset>'),@('calc','--input <dataset...> --output <dataset> --expression <expr>'),@('statistics','--input <dataset> [--band <n>] [--json]'),@('tile','--input <dataset> --output <directory> --zoom <min:max>'))
'Cube'=@(@('info','--input <dataset> [--json]'),@('subset','--input <dataset> --output <dataset> [--select <slice>]'),@('aggregate','--input <dataset> --output <dataset> --by <dimension> --function <name>'),@('merge','--input <dataset...> --output <dataset> --along <dimension>'),@('warp','--input <dataset> --output <dataset> --target <grid>'))
'STAC'=@(@('collections','--url <endpoint> [--json]'),@('search','--url <endpoint> [--bbox <bbox>] [--datetime <range>] [--query <expr>]'),@('assets','--input <item.json> [--json]'),@('download','--input <item.json> --output <directory> [--asset <key>]'))
'GTFS'=@(@('info','--input <feed.zip> [--json]'),@('validate','--input <feed.zip> [--json]'),@('subset','--input <feed.zip> --output <feed.zip> [--route <id>]'),@('export','--input <feed.zip> --output <directory>'))
'Geodesy'=@(@('distance','--from <lon,lat> --to <lon,lat> [--method <name>]'),@('bearing','--from <lon,lat> --to <lon,lat>'),@('destination','--from <lon,lat> --bearing <degrees> --distance <metres>'),@('polygon-area','--input <dataset> [--layer <name>]'))
'Classify'=@(@('equal','--input <values> --classes <n>'),@('quantile','--input <values> --classes <n>'),@('jenks','--input <values> --classes <n>'),@('pretty','--input <values> --classes <n>')) }
[xml]$x=@"
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" Title="RTDAL Toolbox" Width="1000" Height="640" WindowStartupLocation="CenterScreen"><Grid Margin="20"><Grid.ColumnDefinitions><ColumnDefinition Width="210"/><ColumnDefinition Width="*"/></Grid.ColumnDefinitions><StackPanel><TextBlock Text="RTDAL" FontSize="30" FontWeight="Bold"/><TextBlock Text="Toolbox"/><ListBox Name="Category" Margin="0,12,0,0"/></StackPanel><StackPanel Grid.Column="1" Margin="22,0,0,0"><TextBlock Text="Function" FontWeight="Bold"/><ComboBox Name="Function" Margin="0,6,0,14"/><Expander Header="Advanced options" IsExpanded="True"><TextBox Name="Options" Padding="10" IsReadOnly="True" TextWrapping="Wrap"/></Expander><TextBlock Text="Command preview" FontWeight="Bold" Margin="0,18,0,4"/><TextBox Name="Command" Padding="10" FontFamily="Consolas" IsReadOnly="True"/><StackPanel Orientation="Horizontal" HorizontalAlignment="Right" Margin="0,15,0,0"><Button Name="Copy" Content="Copy command" Padding="14,7" Margin="0,0,8,0"/><Button Name="Help" Content="Open CLI help" Padding="14,7"/></StackPanel></StackPanel></Grid></Window>
"@
$r=New-Object System.Xml.XmlNodeReader $x;$w=[Windows.Markup.XamlReader]::Load($r);Add-Type -AssemblyName System.Windows.Forms;$c=$w.FindName('Category');$f=$w.FindName('Function');$o=$w.FindName('Options');$p=$w.FindName('Command');$catalog.Keys|Sort-Object|%{[void]$c.Items.Add($_)};$update={ $f.Items.Clear();$catalog[$c.SelectedItem]|%{[void]$f.Items.Add($_[0])};$f.SelectedIndex=0 };$show={ $row=@($catalog[$c.SelectedItem]|?{$_[0]-eq$f.SelectedItem})[0];$o.Text=$row[1];$p.Text='"'+$RTDALPath+'" '+$c.SelectedItem.ToString().ToLower()+' '+$row[0]+' '+$row[1] };$c.Add_SelectionChanged($update);$f.Add_SelectionChanged($show);$w.FindName('Copy').Add_Click({[Windows.Clipboard]::SetText($p.Text)});$w.FindName('Help').Add_Click({Start-Process cmd.exe -ArgumentList '/k',('"'+$RTDALPath+'" help')});$w.FindName('BrowseInput').Add_Click({$d=New-Object System.Windows.Forms.OpenFileDialog;if($d.ShowDialog()-eq'OK'){$w.FindName('Input').Text=$d.FileName}});$w.FindName('BrowseOutput').Add_Click({$d=New-Object System.Windows.Forms.SaveFileDialog;if($d.ShowDialog()-eq'OK'){$w.FindName('Output').Text=$d.FileName}});$c.SelectedIndex=0;[void]$w.ShowDialog()